# Generated by Django 5.2.9 on 2025-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre', models.CharField(max_length=50)),
                ('tube', models.CharField(max_length=50)),
                ('tyre_valve', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
